"""Generating and checking rider credentials.

A rider's password is generated by the server, shown to the merchant once, and
stored only as a hash. The merchant can regenerate it whenever they like, which
is what gives them permanent practical visibility - they can always produce a
working password for a rider - without a recoverable copy sitting in the
database for a backup to leak.

Passwords are readable on purpose. A merchant reads one aloud, or writes it on
a slip, and a rider types it into a phone with one hand. A random string of
symbols would be copied down wrong, and the workaround for that is everybody
sharing one password.
"""

import secrets

from app.modules.auth.passwords import (  # noqa: F401  (re-exported, see below)
    hash_password,
    hash_password_async,
    verify_password,
    verify_password_async,
)

# Short, unambiguous, and nothing that reads as an insult when paired at random.
_ADJECTIVES = (
    "swift brave calm clever bright eager fair gentle happy keen lively merry noble "
    "proud quick royal sharp steady sunny warm wise zesty bold crisp"
).split()

_NOUNS = (
    "mango tiger falcon river comet pepper ginger cedar lotus monsoon panther "
    "almond cashew saffron jasmine bamboo coral dune ember harbour island "
    "kite lantern meadow"
).split()


def generate_password() -> str:
    """A readable password with roughly 34 bits of entropy.

    24 adjectives x 24 nouns x 9000 numbers. That is not a lot on its own, which
    is why it is paired with a hard, fail-closed per-IP rate limit on the login
    route - five attempts a minute, thirty an hour - rather than being left to
    stand by itself. Regenerating is one tap, so a rider who shares theirs
    around costs the merchant nothing to fix.
    """
    return (
        f"{secrets.choice(_ADJECTIVES)}-{secrets.choice(_NOUNS)}-"
        f"{secrets.randbelow(9000) + 1000}"
    )


def suggest_login_id(display_name: str) -> str:
    """A login id derived from the rider's name, e.g. Amit Kumar -> amit-4821.

    The number is there because login ids are unique across every stall, so two
    stalls both hiring an Amit must not collide. Callers retry on collision.
    """
    first = "".join(ch for ch in display_name.strip().split(" ")[0].lower() if ch.isalnum())
    stem = first[:16] or "rider"
    return f"{stem}-{secrets.randbelow(9000) + 1000}"


# hash_password_async and verify_password_async used to be defined here. They
# moved to app.modules.auth.passwords, beside the sync pair they wrap, once stall
# owners needed them too, and are re-exported above so every existing rider call
# site keeps working unchanged.
